export const tablePurchaseInvoiceFields = [
  {
    key: "accountingDate",
    label: "Ngày hạch toán",
    width: "120px",
    type: "date",
  },
  { key: "documentDate", label: "Ngày chứng từ", width: "120px", type: "date" },
  {
    key: "receiptVoucherNumber",
    label: "Số chứng từ phiếu nhập",
    searchable: true,
    width: "160px",
  },
  {
    key: "documentNumber",
    label: "Số chứng từ",
    searchable: true,
    width: "120px",
  },
  {
    key: "invoiceNumber",
    label: "Số hóa đơn",
    searchable: true,
    width: "120px",
  },
  {
    key: "supplierCode",
    label: "Mã nhà cung cấp",
    searchable: true,
    width: "120px",
  },
  {
    key: "supplierName",
    label: "Nhà cung cấp",
    searchable: true,
    width: "200px",
  },
  { key: "description", label: "Diễn giải", searchable: true, width: "200px" },
  {
    key: "totalAmount",
    label: "Tổng tiền hàng",
    width: "120px",
    align: "right",
    type: "currency",
  },
  {
    key: "discountAmount",
    label: "Tiền chiết khấu",
    width: "120px",
    align: "right",
    type: "currency",
  },
  {
    key: "vatAmount",
    label: "Tiền thuế GTGT",
    width: "120px",
    align: "right",
    type: "currency",
  },
  {
    key: "totalPayment",
    label: "Tổng tiền thanh toán",
    width: "140px",
    align: "right",
    type: "currency",
  },
  {
    key: "purchasingCost",
    label: "Chi phí mua hàng",
    width: "140px",
    align: "right",
    type: "currency",
  },
  {
    key: "warehouseValue",
    label: "Giá trị nhập kho",
    width: "140px",
    align: "right",
    type: "currency",
  },
  {
    key: "invoiceReceived",
    label: "Nhận hóa đơn",
    width: "120px",
    align: "center",
    type: "boolean",
  },
  {
    key: "isPurchasingCost",
    label: "Là chi phí mua hàng",
    width: "140px",
    align: "center",
    type: "boolean",
  },
  {
    key: "documentType",
    label: "Loại chứng từ",
    searchable: true,
    width: "140px",
  },
];

export const mockDataPurchaseInvoice = [
  {
    _id: 1,
    accountingDate: "2021-01-01",
    documentDate: "2021-01-01",
    receiptVoucherNumber: "INV-001",
    documentNumber: "INV-001",
    invoiceNumber: "INV-001",
    invoiceDate: "2021-01-01",
    supplierCode: "SUP-001",
    supplierName: "Supplier 1",
    description: "Description 1",
    totalAmount: 100000,
    discountAmount: 10000,
    vatAmount: 10000,
    totalPayment: 100000,
    purchasingCost: 10000,
    warehouseValue: 10000,
    invoiceReceived: true,
    isPurchasingCost: true,
    documentType: "Invoice",
  },
  {
    _id: 2,
    accountingDate: "2021-01-01",
    documentDate: "2021-01-01",
    receiptVoucherNumber: "INV-002",
    documentNumber: "INV-002",
    invoiceNumber: "INV-002",
    supplierCode: "SUP-002",
    supplierName: "Supplier 2",
    description: "Description 2",
    totalAmount: 200000,
    discountAmount: 20000,
    vatAmount: 20000,
    totalPayment: 200000,
    purchasingCost: 20000,
    warehouseValue: 20000,
    invoiceReceived: true,
    isPurchasingCost: true,
    documentType: "Invoice",
  },
];
